### ISSUE TITLE
Show minted data NFTs in the UI

### ISSUE THREAD

**Issue by mike-audi** [tiki/money#45]
As a user I want to see my NFTs as they are minted.

Acceptance Criteria:
- For each new NFT, a record of the NFT should be displayed in the wallet UI

**Comment by mike-audi** [comment]
![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-05-18 at 00 12 34](https://user-images.githubusercontent.com/3769672/168961917-d355cc06-b4fd-4b30-8085-6c16dbac5845.png)
![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-05-18 at 00 12 37](https://user-images.githubusercontent.com/3769672/168961920-83d3df00-7c82-4795-8c57-8c2d829ddd85.png)

**Comment by ricardobrg** [comment]
inifite scroll

![Simulator Screen Recording - iPhone 8 - 2022-05-18 at 11 42 45](https://user-images.githubusercontent.com/8357343/169069636-095adc15-64c8-4480-86bc-0e59727e60ba.gif)
