### ISSUE TITLE
Implement bottom sheet UI for money sdk

### ISSUE THREAD

**Issue by ricardobrg** [tiki/money#7]
Implement bottom sheet UI with header + transaction list + detail UI.

Acceptance criteria
1. Example app running with bottom sheet.
2. Bottom sheet expands upon scrolling.
3. Detail UI opens a new bottom sheet on top of the list.

**Comment by sfaria27** [comment]
@ricardobrg to add screen capture

**Comment by ricardobrg** [comment]
https://user-images.githubusercontent.com/8357343/156237106-60afe40c-b3c5-4d99-9657-9f0fd4725a7f.mp4
